# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Idm_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11Idm_service.proto\"$\n\x11\x44\x65leteUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"H\n\x11UpdateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0f\n\x07id_user\x18\x03 \x01(\t\"3\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"D\n\x12UpdateUserResponse\x12\x0f\n\x07id_user\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"D\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"2\n\rTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x89\x01\n\rSignUpRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x12\n\nfirst_name\x18\x05 \x01(\t\x12\r\n\x05phone\x18\x06 \x01(\t\x12\r\n\x05\x65mail\x18\x07 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x08 \x01(\t\"V\n\x0eSignUpResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x0f\n\x07id_user\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\x05\x32\xfb\x01\n\nIDMService\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12,\n\x0bVerifyToken\x12\r.TokenRequest\x1a\x0e.TokenResponse\x12)\n\x06SignUp\x12\x0e.SignUpRequest\x1a\x0f.SignUpResponse\x12\x35\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponse\x12\x35\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Idm_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DELETEUSERREQUEST']._serialized_start=21
  _globals['_DELETEUSERREQUEST']._serialized_end=57
  _globals['_UPDATEUSERREQUEST']._serialized_start=59
  _globals['_UPDATEUSERREQUEST']._serialized_end=131
  _globals['_DELETEUSERRESPONSE']._serialized_start=133
  _globals['_DELETEUSERRESPONSE']._serialized_end=184
  _globals['_UPDATEUSERRESPONSE']._serialized_start=186
  _globals['_UPDATEUSERRESPONSE']._serialized_end=254
  _globals['_LOGINREQUEST']._serialized_start=256
  _globals['_LOGINREQUEST']._serialized_end=306
  _globals['_LOGINRESPONSE']._serialized_start=308
  _globals['_LOGINRESPONSE']._serialized_end=376
  _globals['_TOKENREQUEST']._serialized_start=378
  _globals['_TOKENREQUEST']._serialized_end=407
  _globals['_TOKENRESPONSE']._serialized_start=409
  _globals['_TOKENRESPONSE']._serialized_end=459
  _globals['_SIGNUPREQUEST']._serialized_start=462
  _globals['_SIGNUPREQUEST']._serialized_end=599
  _globals['_SIGNUPRESPONSE']._serialized_start=601
  _globals['_SIGNUPRESPONSE']._serialized_end=687
  _globals['_IDMSERVICE']._serialized_start=690
  _globals['_IDMSERVICE']._serialized_end=941
# @@protoc_insertion_point(module_scope)
