# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import Idm_service_pb2 as Idm__service__pb2


class IDMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/IDMService/Login',
                request_serializer=Idm__service__pb2.LoginRequest.SerializeToString,
                response_deserializer=Idm__service__pb2.LoginResponse.FromString,
                )
        self.VerifyToken = channel.unary_unary(
                '/IDMService/VerifyToken',
                request_serializer=Idm__service__pb2.TokenRequest.SerializeToString,
                response_deserializer=Idm__service__pb2.TokenResponse.FromString,
                )
        self.SignUp = channel.unary_unary(
                '/IDMService/SignUp',
                request_serializer=Idm__service__pb2.SignUpRequest.SerializeToString,
                response_deserializer=Idm__service__pb2.SignUpResponse.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/IDMService/DeleteUser',
                request_serializer=Idm__service__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=Idm__service__pb2.DeleteUserResponse.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/IDMService/UpdateUser',
                request_serializer=Idm__service__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=Idm__service__pb2.UpdateUserResponse.FromString,
                )
        self.GetUserData = channel.unary_unary(
                '/IDMService/GetUserData',
                request_serializer=Idm__service__pb2.GetUserRequest.SerializeToString,
                response_deserializer=Idm__service__pb2.GetUserResponse.FromString,
                )


class IDMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IDMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=Idm__service__pb2.LoginRequest.FromString,
                    response_serializer=Idm__service__pb2.LoginResponse.SerializeToString,
            ),
            'VerifyToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyToken,
                    request_deserializer=Idm__service__pb2.TokenRequest.FromString,
                    response_serializer=Idm__service__pb2.TokenResponse.SerializeToString,
            ),
            'SignUp': grpc.unary_unary_rpc_method_handler(
                    servicer.SignUp,
                    request_deserializer=Idm__service__pb2.SignUpRequest.FromString,
                    response_serializer=Idm__service__pb2.SignUpResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=Idm__service__pb2.DeleteUserRequest.FromString,
                    response_serializer=Idm__service__pb2.DeleteUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=Idm__service__pb2.UpdateUserRequest.FromString,
                    response_serializer=Idm__service__pb2.UpdateUserResponse.SerializeToString,
            ),
            'GetUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserData,
                    request_deserializer=Idm__service__pb2.GetUserRequest.FromString,
                    response_serializer=Idm__service__pb2.GetUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IDMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IDMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IDMService/Login',
            Idm__service__pb2.LoginRequest.SerializeToString,
            Idm__service__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IDMService/VerifyToken',
            Idm__service__pb2.TokenRequest.SerializeToString,
            Idm__service__pb2.TokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SignUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IDMService/SignUp',
            Idm__service__pb2.SignUpRequest.SerializeToString,
            Idm__service__pb2.SignUpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IDMService/DeleteUser',
            Idm__service__pb2.DeleteUserRequest.SerializeToString,
            Idm__service__pb2.DeleteUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IDMService/UpdateUser',
            Idm__service__pb2.UpdateUserRequest.SerializeToString,
            Idm__service__pb2.UpdateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IDMService/GetUserData',
            Idm__service__pb2.GetUserRequest.SerializeToString,
            Idm__service__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
